---
sonarr_config_home: "{{sonarr_home}}/config"
sonarr_data_home: "{{sonarr_home}}/data"
sonarr_container_cpu_limit: "1"
sonarr_container_image: "{{sonarr_container_repo}}:{{sonarr_container_image_tag}}"
sonarr_container_mem_limit: "1g"
sonarr_container_network_name: "sonarr"
sonarr_container_repo: "ghcr.io/hotio/sonarr"
sonarr_container_image_tag: "latest"
sonarr_home: "/opt/podman-sonarr"
sonarr_nginx_http_port: 8989
sonarr_nginx_https_port: 0
sonarr_nginx_server_name: "sonarr.*"

sonarr_timezone: "Etc/UTC"
sonarr_unix_group_id: "{{sonarr_unix_user_id}}"
sonarr_unix_group_name: "{{sonarr_unix_user_name}}"
sonarr_unix_user_id: 8989
sonarr_unix_user_name: "sonarr"
sonarr_unix_umask: "002"
sonarr_unix_mode_config_dir: "0770"

sonarr_container_devices: []

# extra container variables to set
sonarr_container_env: {}

# network ports to expose
sonarr_container_ports:
  - "{{sonarr_nginx_http_port}}:{{sonarr_nginx_http_port}}"

# extra container volumes to mount
sonarr_container_volumes:
  - "{{sonarr_config_home}}:/config"
  - "{{sonarr_data_home}}:/data"

sonarr_container_volumes_extra: {}
