---
scrutiny_config_home: "{{scrutiny_home}}/config"
scrutiny_data_home: "{{scrutiny_home}}/data"
scrutiny_container_cpu_limit: "1"
scrutiny_container_image: "{{scrutiny_container_repo}}:{{scrutiny_container_image_tag}}"
scrutiny_container_mem_limit: "1g"
scrutiny_container_network_name: "scrutiny"
scrutiny_container_repo: "ghcr.io/analogj/scrutiny"
scrutiny_container_image_tag: "master-omnibus"
scrutiny_home: "/opt/docker-scrutiny"
scrutiny_nginx_http_port: 2999
scrutiny_nginx_https_port: 0
scrutiny_nginx_server_name: "scrutiny.*"

scrutiny_timezone: "Etc/UTC"
scrutiny_unix_group_id: "{{scrutiny_unix_user_id}}"
scrutiny_unix_group_name: "{{scrutiny_unix_user_name}}"
scrutiny_unix_user_id: <UID>
scrutiny_unix_user_name: "scrutiny"
scrutiny_unix_umask: "002"
scrutiny_unix_mode_config_dir: "0770"

scrutiny_container_devices: []

# extra container variables to set
scrutiny_container_env:
  COLLECTOR_RUN_STARTUP: "true"

# network ports to expose
scrutiny_container_ports:
  - "{{scrutiny_nginx_http_port}}:{{scrutiny_nginx_http_port}}"

# extra container volumes to mount
scrutiny_container_volumes:
 {}
scrutiny_container_volumes_extra: {}
