#!/usr/bin/env ansible-playbook
---
# source: https://raw.githubusercontent.com/azlux/log2ram/master/ansible_playbook/install_log2ram.yml
- name: Add rsync as pre-requisite
  apt:
    name: rsync
  when: log2ram_use_rsync

- name: Install GnuPG
  apt:
    name: gnupg

- name: Add gpg key
  shell:
    cmd: >
      curl -fsSL {{ log2ram_gpg }} | gpg --dearmor --yes -o {{ log2ram_keyring }}
    creates: "{{ log2ram_keyring }}"

- name: Add apt repository
  apt_repository:
    repo: "{{ log2ram_apt_repository }}"
    filename: log2ram
  register: log2ram_apt_repo

- name: Update apt cache
  apt:
    update_cache: true
  when: log2ram_apt_repo is changed

- name: Install log2ram
  apt:
    name: log2ram
  notify: restart-log2ram

- name: Set config options
  lineinfile:
    path: /etc/log2ram.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: true
  loop:
    - { regexp: "^SIZE=(.*)$", line: "SIZE={{ log2ram_size }}" }
    - { regexp: "USE_RSYNC=(.*)$", line: "USE_RSYNC={{ log2ram_use_rsync }}" }
    - {
        regexp: "^NOTIFICATION=(.*)$",
        line: "NOTIFICATION={{ log2ram_notification }}",
      }
    - {
        regexp: "^NOTIFICATION_COMMAND=(.*)$",
        line: "NOTIFICATION_COMMAND={{ log2ram_notification_command }}",
      }
    - {
        regexp: "^PATH_DISK=(.*)$",
        line: 'PATH_DISK="{{ log2ram_path_disk }}"',
      }
    - { regexp: "^ZL2R=(.*)$", line: "ZL2R={{ log2ram_use_z2lr|lower }}" }
    - { regexp: "^COMP_ALG=(.*)$", line: "COMP_ALG={{ log2ram_comp_alg }}" }
    - {
        regexp: "^LOG_DISK_SIZE=(.*)$",
        line: "LOG_DISK_SIZE={{ log2ram_log_disk_size }}",
      }
  notify: restart-log2ram
