---
grafana_config_home: "{{grafana_home}}/config"
grafana_data_home: "{{grafana_home}}/data"
grafana_container_cpu_limit: "1"
grafana_container_image: "{{grafana_container_repo}}:{{grafana_container_image_tag}}"
grafana_container_mem_limit: "1g"
grafana_container_network_name: "grafana"
grafana_container_repo: "grafana/grafana"
grafana_container_image_tag: "latest"
grafana_home: "/opt/podman-grafana"
grafana_nginx_http_port: 3000
grafana_nginx_https_port: 0
grafana_nginx_server_name: "grafana.*"

grafana_timezone: "Etc/UTC"
grafana_unix_group_id: "{{grafana_unix_user_id}}"
grafana_unix_group_name: "{{grafana_unix_user_name}}"
grafana_unix_user_id: 3000
grafana_unix_user_name: "grafana"
grafana_unix_umask: "002"
grafana_unix_mode_config_dir: "0770"

grafana_container_devices: []

# extra container variables to set
grafana_container_env: {}

# network ports to expose
grafana_container_ports:
  - "{{grafana_nginx_http_port}}:{{grafana_nginx_http_port}}"

# extra container volumes to mount
grafana_container_volumes:
  - "{{grafana_config_home}}:/config"
  - "{{grafana_data_home}}:/data"

grafana_container_volumes_extra: {}
