---
heimdall_config_home: "{{heimdall_home}}/config"
heimdall_data_home: "{{heimdall_home}}/data"
heimdall_container_cpu_limit: "1"
heimdall_container_image: "{{heimdall_container_repo}}:{{heimdall_container_image_tag}}"
heimdall_container_mem_limit: "1g"
heimdall_container_network_name: "heimdall"
heimdall_container_repo: "lscr.io/linuxserver/heimdall"
heimdall_container_image_tag: "latest"
heimdall_home: "/opt/docker-heimdall"
heimdall_nginx_http_port: 8081
heimdall_nginx_https_port: 0
heimdall_nginx_server_name: "heimdall.*"

heimdall_timezone: "Etc/UTC"
heimdall_unix_group_id: "{{heimdall_unix_user_id}}"
heimdall_unix_group_name: "{{heimdall_unix_user_name}}"
heimdall_unix_user_id: 8081
heimdall_unix_user_name: "heimdall"
heimdall_unix_umask: "002"
heimdall_unix_mode_config_dir: "0770"

heimdall_container_devices: []

# extra container variables to set
heimdall_container_env: {}

# network ports to expose
heimdall_container_ports:
  - "{{heimdall_nginx_http_port}}:{{heimdall_nginx_http_port}}"

# extra container volumes to mount
heimdall_container_volumes:
  - "{{heimdall_config_home}}:/config"
  - "{{heimdall_data_home}}:/data"

heimdall_container_volumes_extra: {}
