- name: ensure fonts are installed [Debian]
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.import_tasks: install-debian.yaml

- name: ensure fonts are installed [Darwin]
  when: ansible_facts['os_family'] == "Darwin"
  ansible.builtin.import_tasks: install-darwin.yaml
