---
mariadb_config_home: "{{mariadb_home}}/config"
mariadb_data_home: "{{mariadb_home}}/data"
mariadb_container_cpu_limit: "1"
mariadb_container_image: "{{mariadb_container_repo}}:{{mariadb_container_image_tag}}"
mariadb_container_mem_limit: "1g"
mariadb_container_network_name: "mariadb"
mariadb_container_repo: "lscr.io/linuxserver/mariadb"
mariadb_container_image_tag: "latest"
mariadb_home: "/opt/podman-mariadb"
mariadb_nginx_http_port: 0
mariadb_nginx_https_port: 0

mariadb_timezone: "Etc/UTC"
mariadb_unix_group_id: "{{mariadb_unix_user_id}}"
mariadb_unix_group_name: "{{mariadb_unix_user_name}}"
mariadb_unix_user_id: 3306
mariadb_unix_user_name: "mariadb"
mariadb_unix_umask: "002"
mariadb_unix_mode_config_dir: "0770"

mariadb_container_devices: []

# extra container variables to set
mariadb_container_env: {}

# network ports to expose
mariadb_container_ports:
  - "3306:3306/tcp"

# extra container volumes to mount
mariadb_container_volumes:
  - "{{mariadb_config_home}}:/config"
  - "{{mariadb_data_home}}:/data"

mariadb_container_volumes_extra: {}
