---
syncthing_config_home: "{{syncthing_home}}/config"
syncthing_data_home: "{{syncthing_home}}/data"
syncthing_container_cpu_limit: "1"
syncthing_container_image: "{{syncthing_container_repo}}:{{syncthing_container_image_tag}}"
syncthing_container_mem_limit: "1g"
syncthing_container_network_name: "syncthing"
syncthing_container_repo: "lscr.io/linuxserver/syncthing"
syncthing_container_image_tag: "latest"
syncthing_home: "/opt/podman-syncthing"
syncthing_nginx_http_port: 8384
syncthing_nginx_https_port: 0
syncthing_nginx_server_name: "syncthing.*"

syncthing_timezone: "Etc/UTC"
syncthing_unix_group_id: "{{syncthing_unix_user_id}}"
syncthing_unix_group_name: "{{syncthing_unix_user_name}}"
syncthing_unix_user_id: <UID>
syncthing_unix_user_name: "syncthing"
syncthing_unix_umask: "027"
syncthing_unix_mode_config_dir: "0750"

syncthing_container_devices: []

# extra container variables to set
syncthing_container_env: {}

# network ports to expose
syncthing_container_ports:
  - "{{syncthing_nginx_http_port}}:{{syncthing_nginx_http_port}}"
  - "22000:22000/tcp"
  - "22000:22000/udp"
  - "21027:21027/udp"

# extra container volumes to mount
syncthing_container_volumes:
  - "{{syncthing_config_home}}:/config"
  - "{{syncthing_data_home}}:/data"

syncthing_container_volumes_extra: {}
