- name: install podman and some management sugar
  apt:
    name:
      - cockpit
      - cockpit-podman
      - podman
      - podman-compose
      - podman-docker
  notify: restart cockpit
  tags: [podman]

- name: ensure a named podman network exists
  containers.podman.podman_network:
    name: "{{podman_network_name}}"
  become: true
  notify: restart cockpit
  tags: [podman]
