---
- name: "create service group"
  ansible.builtin.group:
    name: "{{heimdall_unix_group_name}}"
    gid: "{{heimdall_unix_group_id}}"
    state: present
  register: transmission_group_results

- name: "create service home"
  ansible.builtin.file:
    state: directory
    path: "{{heimdall_home}}"
    owner: root
    group: adm
    mode: 0755
  notify: "restart docker-heimdall"

- name: "create user"
  ansible.builtin.user:
    name: "{{heimdall_unix_user_name}}"
    state: present
    uid: "{{heimdall_unix_user_id}}"
    group:  "{{heimdall_unix_group_name}}"
    shell: /usr/sbin/nologin
    home: "{{heimdall_home}}"
    create_home: false

- name: template compose file
  ansible.builtin.template:
    src: "compose.yaml.j2"
    dest: "{{heimdall_home}}/compose.yaml"
    owner: root
    group: adm
    mode: 0640
  notify: "restart docker-heimdall"
  tags: [compose]

- name: "create config dir"
  ansible.builtin.file:
    state: directory
    path: "{{heimdall_config_home}}"
    owner: "{{heimdall_unix_user_name}}"
    group: "{{heimdall_unix_group_name}}"
    mode: "{{heimdall_unix_mode_config_dir}}"
  notify: "restart docker-heimdall"

- name: template systemd service
  ansible.builtin.template:
    src: "docker-heimdall.service.j2"
    dest: "/lib/systemd/system/docker-heimdall.service"
  notify: "restart docker-heimdall"

- name: enable and start docker-heimdall
  ansible.builtin.systemd_service:
    name: docker-heimdall
    daemon_reload: true
    enabled: true
    masked: no
    state: started
  async: 60
  poll: 5

- ansible.builtin.include_tasks: "_nginx.yaml"
  tags: [nginx]
