---
jellyfin_config_home: "{{jellyfin_home}}/config"
jellyfin_data_home: "{{jellyfin_home}}/data"
jellyfin_container_cpu_limit: "1"
jellyfin_container_image: "{{jellyfin_container_repo}}:{{jellyfin_container_image_tag}}"
jellyfin_container_mem_limit: "1g"
jellyfin_container_network_name: "jellyfin"
jellyfin_container_repo: "linuxserver/jellyfin"
jellyfin_container_image_tag: "latest"
jellyfin_home: "/opt/podman-jellyfin"
jellyfin_nginx_http_port: 8096
jellyfin_nginx_https_port: 0
jellyfin_nginx_server_name: "jellyfin.*"

jellyfin_timezone: "Etc/UTC"
jellyfin_unix_group_id: "{{jellyfin_unix_user_id}}"
jellyfin_unix_group_name: "{{jellyfin_unix_user_name}}"
jellyfin_unix_user_id: 8096
jellyfin_unix_user_name: "jellyfin"
jellyfin_unix_umask: "002"
jellyfin_unix_mode_config_dir: "0770"

jellyfin_container_devices: []

# extra container variables to set
jellyfin_container_env: {}

# network ports to expose
jellyfin_container_ports:
  - "{{jellyfin_nginx_http_port}}:{{jellyfin_nginx_http_port}}"

# extra container volumes to mount
jellyfin_container_volumes:
  - "{{jellyfin_config_home}}:/config"
  - "{{jellyfin_data_home}}:/data"

jellyfin_container_volumes_extra: {}
