---
portainer_config_home: "{{portainer_home}}/config"
portainer_data_home: "{{portainer_home}}/data"
portainer_container_cpu_limit: "1"
portainer_container_image: "{{portainer_container_repo}}:{{portainer_container_image_tag}}"
portainer_container_mem_limit: "1g"
portainer_container_network_name: "portainer"
portainer_container_repo: "portainer/portainer-ce"
portainer_container_image_tag: "latest"
portainer_home: "/opt/podman-portainer"
portainer_nginx_http_port: 9443
portainer_nginx_https_port: 0
portainer_nginx_server_name: "portainer.*"

portainer_timezone: "Etc/UTC"
portainer_unix_group_id: "{{portainer_unix_user_id}}"
portainer_unix_group_name: "{{portainer_unix_user_name}}"
portainer_unix_user_id: 9443
portainer_unix_user_name: "portainer"
portainer_unix_umask: "002"
portainer_unix_mode_config_dir: "0750"

portainer_container_devices: []

# extra container variables to set
portainer_container_env: {}

# network ports to expose
portainer_container_ports:
  - "{{portainer_nginx_http_port}}:{{portainer_nginx_http_port}}"

# extra container volumes to mount
portainer_container_volumes:
  - "{{portainer_config_home}}:/config"
  - "/var/run/container.sock:/var/run/container.sock"

portainer_container_volumes_extra: {}
